### ISSUE TITLE
TypeError: callback is not a function when running examples

### ISSUE THREAD

**Issue by lbonini** [SloRunner/ethermine-api#8]
Hello, I´m just cloned the repository and after installing the dependencies I tried to run the examples.
It looks that first it runs the code, but then it reports an error related to the function callback().
Sorry, I´ve just started using NodeJS, so maybe this is something simple.
This is the error:

ethermine-api\example (master)
λ node miner.js
false { status: 'OK', data: [] }
false { status: 'OK', data: [] }
false { status: 'OK', data: [] }
C:\laragon\www\ethermine-api\src\index.js:59
                callback(false, body)
                ^

TypeError: callback is not a function
    at Request._callback (C:\laragon\www\ethermine-api\src\index.js:59:17)
    at Request.self.callback (C:\laragon\www\ethermine-api\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\laragon\www\ethermine-api\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\laragon\www\ethermine-api\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Thank you in advance.

**Comment by SloRunner** [comment]
Which NodeJS version do you use?

**Comment by SloRunner** [comment]
Fixed
